version: '3'
services:
  fortune-cookie-backend:
    build: ./backend/.
    restart: unless-stopped
  fortune-cookie-frontend:
    build: ./frontend/.
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - fortune-cookie-backend
    environment:
      BACKEND_PORT: "9000"
      BACKEND_DNS: "fortune-cookie-backend"


