version: '3'
services:
  backend:
    build: ./backend/.
    restart: unless-stopped
  frontend:
    build: ./frontend/.
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      BACKEND_PORT: "9000" #`BACKEND_PORT` - Port of the backend. Default: 9000
      BACKEND_DNS: "backend" #`BACKEND_DNS` - DNS of the backend. Default: localhost


