apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ${DOCKER_HUB_USERNAME}/frontend:${{ github.sha }}
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_PORT
          value: '8081'