apiVersion: v1
kind: Service
metadata:
  name: fortune-cookie-frontend
spec:
  selector:
    app: fortune-cookie-frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort