apiVersion: v1
kind: Service
metadata:
  labels:
    app: fortune-cookie-backend
  name: fortune-cookie-backend
spec:
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
selector:
  app: fortune-cookie-backend
type: ClusterIP
status:
  loadBalancer: {}