apiVersion: v1
kind: Service
metadata:
  labels:
    app: fortune-cookie-frontend
  name: fortune-cookie-frontend
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
      nodePort: 30001
  selector:
    app: fortune-cookie-frontend
  type: NodePort