name: Automated Tests

on:
  push:
    branches: 
    - '*'
  pull_request:
    branches:
    - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Go 1.21.0
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.0
    - name: Run Tests
      run: |
        cd frontend
        go test
        cd ../backend
        go test
