name: Automated Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main 

jobs:
  test:
    name: Test Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build the frontend
        run: cd frontend && go build

      - name: Run Frontend Tests
        run: cd frontend && go test
