name: Deploy to Kubernetes

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      run: docker login -u ${{ env.DOCKER_USERNAME }} -p ${{ env.DOCKER_PASSWORD }}
    - name: Build and push backend image
      run: |
        docker build -t ${DOCKER_USERNAME}/backend:${{ github.sha }} ./backend
        docker push ${DOCKER_USERNAME}/backend:${{ github.sha }}
    - name: Build and push frontend image
      run: |
        docker build -t ${DOCKER_USERNAME}/frontend:${{ github.sha }} ./frontend
        docker push ${DOCKER_USERNAME}/frontend:${{ github.sha }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Create kubeconfig
      run: |
        mkdir ${HOME}/.kube
        echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config
        cat ${HOME}/.kube/config
    - name: Use context
      run: kubectl config use-context ${{ secrets.KUBE_CONTEXT }}
    - name: Deploy to K8s
      run: kubectl apply -f k8s/
