name: Publish Docker image

on:
  push:
    branches: 
      - main_GH-3_rhe_kubernetes

jobs:
  build_artifacts:
    name: Build Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build the backend
        run: cd backend && go build

      - name: Build the frontend
        run: cd frontend && go build

      - name: Archive the frontend build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Frontend
          path: ./frontend
      
      - name: Archive the backend build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Backend
          path: ./backend

  push_frontend:
    name: Push frontend Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: [build_artifacts]
    steps:
      - name: Download frontend artifact
        uses: actions/download-artifact@v3
        with:
          name: Frontend
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fortune-cookie-frontend:latest

  push_backend:
    name: Push backend Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: [build_artifacts]
    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v3
        with:
          name: Backend
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fortune-cookie-backend:latest
    
  deploy_k8s:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [push_frontend, push_backend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Kubernetes
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig
          kubectl --kubeconfig kubeconfig apply -f ./k8s
