name: Publish Docker image

on:
  push:
    branches: 
      - main_GH-4_osb_container-registry

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          dockerfile: Dockerfile
          push: true
          tags: latest
          registry: docker.io
          repository: helleberg/fortune-cookie-frontend